# Generated by Django 5.1.2 on 2024-10-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagSiteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=160)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('site_description', models.TextField()),
                ('meta_title', models.CharField(default='Default Meta Title', max_length=60)),
                ('meta_description', models.TextField(max_length=320)),
                ('founder', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('old_url', models.SlugField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('indexable', models.BooleanField(default=True)),
                ('tags', models.ManyToManyField(blank=True, to='app_home.tagsitemodel')),
            ],
        ),
    ]
